### ISSUE TITLE
Incompatibility issue

### ISSUE THREAD

**Issue by ghost** [The-Fireplace/Adobe-Blocks#3]
When installed along with [Backpacks](https://minecraft.curseforge.com/projects/forge-backpacks) by Eydamos, the recipe for Stone sticks replaces the one from that mod, resulting in not being able to craft the Backpack Tier II. Maybe you're able to implement compatibility in that case.

Issue also reported [here](https://minecraft.curseforge.com/projects/forge-backpacks/issues).

Minecraft Version: 1.10.2
Adobe Blocks Version: 6.0.3.23
Backpacks Version: 3.0.1

**Comment by The-Fireplace** [comment]
He needs to use OreDictionary if he isn't already. That will make it so stone sticks from either mod work in the recipes from either mod. I have already done everything I can on my end.
