### ISSUE TITLE
Crash after update

### ISSUE THREAD

**Issue by ghost** [The-Fireplace/Adobe-Blocks#6]
When I update Adobe Blocks to the latest version the game crashes on startup.

Minecraft Version: 1.10.2
Forge Version: 12.18.1.2076-universal
Crashing Adobe Blocks Version: 6.0.3.26
Latest Working Version: 6.0.3.23

> ---- Minecraft Crash Report ----
> 
> WARNING: coremods are present:
>   FarseekCoreMod (Farseek-1.1.jar)
>   BetterFoliageLoader (Better-Foliage-2.1.0.jar)
>   AppleCore (AppleCore-2.0.1.jar)
>   IvToolkit (IvToolkit-1.2.8.5.jar)
>   FMLPlugin (Inventory-Tweaks-1.61-58.jar)
>   StreamsCoreMod (Streams-0.2.1.jar)
>   LoadingPluginHardModeTweaks (Hard-Mode-Tweaks-1.2.2.jar)
>   NWRTweak (Redstone-Paste-1.7.4.jar)
> Contact their authors BEFORE contacting forge
> 
> // My bad.
> 
> Time: 12.09.16 12:13
> Description: There was a severe problem during mod loading that has caused the game to fail
> 
> net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/util/IChatComponent
>   at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186)
>   at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:576)
>   at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:216)
>   at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
>   at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
>   at net.minecraft.client.main.Main.main(SourceFile:124)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>   at java.lang.reflect.Method.invoke(Unknown Source)
>   at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
>   at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> Caused by: java.lang.NoClassDefFoundError: net/minecraft/util/IChatComponent
>   at java.lang.Class.forName0(Native Method)
>   at java.lang.Class.forName(Unknown Source)
>   at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:503)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>   at java.lang.reflect.Method.invoke(Unknown Source)
>   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
>   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
>   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
>   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
>   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
>   at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
>   at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>   at java.lang.reflect.Method.invoke(Unknown Source)
>   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
>   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
>   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
>   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
>   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
>   at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
>   at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:545)
>   ... 10 more
> Caused by: java.lang.ClassNotFoundException: net.minecraft.util.IChatComponent
>   at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
>   at java.lang.ClassLoader.loadClass(Unknown Source)
>   at java.lang.ClassLoader.loadClass(Unknown Source)
>   ... 35 more
> Caused by: java.lang.ArrayIndexOutOfBoundsException
> ## A detailed walkthrough of the error, its code path and all known details is as follows:
> 
> -- System Details --
> Details:
>   Minecraft Version: 1.10.2
>   Operating System: Windows 7 (amd64) version 6.1
>   Java Version: 1.8.0_101, Oracle Corporation
>   Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
>   Memory: 3749799912 bytes (3576 MB) / 4260102144 bytes (4062 MB) up to 4260102144 bytes (4062 MB)
>   JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -Xms4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy
>   IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
>   FML: MCP 9.32 Powered by Forge 12.18.1.2076 Optifine OptiFine_1.10.2_HD_U_C3 66 mods loaded, 66 mods active
>   States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
>   UC  mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
>   UC  FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.1.2076.jar) 
>   UC  Forge{12.18.1.2076} [Minecraft Forge](forge-1.10.2-12.18.1.2076.jar) 
>   UC  hardmodetweakscore{1.0.0} [Hard Mode Tweaks Core](minecraft.jar) 
>   UC  ivtoolkit{1.2.8.5} [IvToolkit](minecraft.jar) 
>   UC  adamantium{1.6.3} [Adamantium Mod](Adamantium-Mod-1.6.3.jar) 
>   UC  adobeblocks{6.0.3.26} [Adobe Blocks 2](Adobe-Blocks-6.0.3.26.jar) 
>   UE  adobeblocksvc{1.1} [Adobe Blocks 2 Version Checker](Adobe-Blocks-6.0.3.26.jar) 
>   UC  JEI{3.9.3.252} [Just Enough Items](Just-Enough-Items-3.9.3.252.jar) 
>   UC  AppleCore{2.0.1} [AppleCore](AppleCore-2.0.1.jar) 
>   UC  appleskin{1.0.3} [AppleSkin](AppleSkin-1.0.3.jar) 
>   UC  aquaculture{1.4.0} [Aquaculture](Aquaculture-1.4.0.28.jar) 
>   UC  backpack{3.0.1} [Backpack](Backpacks-3.0.1.jar) 
>   UC  basemetals{2.4.0} [Base Metals](Base-Metals-2.4.0.11.jar) 
>   UC  golems{6.02} [Extra Golems](Extra-Golems-6.02.jar) 
>   UC  golems_metal{6.02.1} [Base Metal Golems](Base-Metal-Golems-6.02.1.jar) 
>   UC  BetterFoliage{2.1.0} [Better Foliage](Better-Foliage-2.1.0.jar) 
>   UC  BetterAchievements{0.3.0.30} [Better Achievements](BetterAchievements-0.3.0.30.jar) 
>   UC  BiomesOPlenty{5.0.0.2085} [Biomes O' Plenty](Biomes-O-Plenty-5.0.0.2085-universal.jar) 
>   UC  birdsnests{1.3} [Bird's Nests](Birds-Nests-1.3.jar) 
>   UC  Bullseye{1.0.3} [Bullseye](Bullseye-1.0.3.jar) 
>   UC  Chameleon{1.10-2.1.7} [Chameleon](Chameleon-2.1.7.jar) 
>   UC  chisel{MC1.9.4-0.0.6.33} [Chisel](Chisel-0.0.6.33.jar) 
>   UC  chiselsandbits{12.1} [Chisels & Bits](Chisels-and-Bits-12.1.jar) 
>   UC  claycraft{3.0} [Claycraft](Claycraft-3.0.jar) 
>   UC  crossbowmod{1.3} [Crossbow Mod](Crossbow-Mod-1.3.jar) 
>   UC  labyrinth{${version}} [Daedalus' Labyrinth](Daedalus-Labyrinth-1.1.jar) 
>   UC  lootablebodies{2.2.0} [DrCyano's Lootable Bodies](DrCyanos-Lootable-Bodies-2.2.0.jar) 
>   UC  enrichedobsidian{1.0} [Enriched Obsidian Mod](Enriched-Obsidian-1.0.jar) 
>   UC  Farseek{1.9.4} [Farseek](Farseek-1.1.jar) 
>   UC  giacomosfoundry{1.3.5} [Giacomo's Foundry](Giacomos-Foundry-1.3.5.jar) 
>   UC  glasscraftmod{1.0} [Glasscraft](Glasscraft-1.0.jar) 
>   UC  glowniummod{1.0.0} [Glownium (Craftable Glowstone)](Glownium-1.0.0.jar) 
>   UC  hardmodetweaks{@1.10-1.2.2@} [Hard Mode Tweaks](Hard-Mode-Tweaks-1.2.2.jar) 
>   UC  hopperducts{1.4.7} [Hopper Ducts](Hopper-Ducts-1.4.7.jar) 
>   UC  inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks](Inventory-Tweaks-1.61-58.jar) 
>   UC  mantle{1.10.2-0.10.4.jenkins163} [Mantle](Mantle-0.10.4.jar) 
>   UC  RadixCore{1.10.2-2.1.3} [RadixCore](RadixCore-2.1.3-universal.jar) 
>   UC  MCA{1.10.2-5.2.3} [Minecraft Comes Alive](Minecraft-Comes-Alive-5.2.3-universal.jar) 
>   UC  MoarGlowstone{1.0.0} [MOAR Glowstone](MOAR-Glowstone-1.0.0.jar) 
>   UC  nethercore{1.10.2-2.0.2} [Nether Core](Nether-Core-2.0.2-Beta3.jar) 
>   UC  netheressence{6.0.1.5} [Nether Essence](Nether-Essence-6.0.1.5.jar) 
>   UC  orespawn{1.1.0} [Ore Spawn](OreSpawn-1.1.0.jar) 
>   UC  harvestcraft{1.9.4-pre} [Pam's HarvestCraft](Pams-HarvestCraft-1.10.2b.jar) 
>   UC  poweradvantage{2.3.0} [Power Advantage](Power-Advantage-2.3.0.jar) 
>   UC  cobwebs{1.0.1} [Realistic Cobwebs Mod](Realistic-Cobwebs-1.0.1.jar) 
>   UC  RTG{1.10.2} [Realistic Terrain Generation](Realistic-Terrain-Generation-4.1.1.2-snapshot-4.jar) 
>   UC  reccomplex{1.0.3} [Recurrent Complex](Recurrent-Complex-1.0.3.jar) 
>   UC  redstonepaste{1.7.4} [Redstone Paste](Redstone-Paste-1.7.4.jar) 
>   UC  Roguelike{1.5.4} [Roguelike Dungeons](Roguelike-Dungeons-1.5.4.jar) 
>   UC  roots{0.202} [Roots](Roots-0.202.0.jar) 
>   UC  slabcraftmod{6.03} [Slabcraft](Slabcraft-6.03.jar) 
>   UC  staircraftmod{6.02} [Staircraft](Staircraft-6.02.jar) 
>   UC  steamadvantage{2.2.0} [Steam Advantage](Steam-Advantage-2.2.0.jar) 
>   UC  StorageDrawers{1.10.2-3.2.7} [Storage Drawers](Storage-Drawers-3.2.7.jar) 
>   UC  Streams{1.9.4} [Streams](Streams-0.2.1.jar) 
>   UC  tesla{1.2.1.49} [TESLA](Tesla-1.2.1.49.jar) 
>   UC  teslaarsenal{1.4} [Tesla Arsenal](Tesla-Arsenal-1.4.jar) 
>   UC  teslacoils{v0.2.1.0} [Tesla Coils](Tesla-Coils-0.2.1.0.jar) 
>   UC  tconstruct{1.10.2-2.4.0.jenkins325} [Tinkers' Construct](Tinkers-Construct-2.4.0.jar) 
>   UC  torcharrowsmod{1.10.2-1} [TorchArrowsMod](Torch-Arrows-1.10.2-1.jar) 
>   UC  Waila{1.7.0} [Waila](Waila-1.7.0-B3.jar) 
>   UC  icse{1.1.0.0} [I Can See Everything](Wawla-2.3.0.203.jar) 
>   UC  wawla{2.3.0.202} [What Are We Looking At](Wawla-2.3.0.203.jar) 
>   UC  waystones{2.0.4} [Waystones](Waystones-2.0.4.jar) 
>   UC  wtfcore{1.10_BetaX} [wtfcore](WTFs-Expedition-1.10.2-Beta11.4.jar) 
>   Loaded coremods (and transformers): 
> FarseekCoreMod (Farseek-1.1.jar)
>   farseek.core.FarseekClassTransformer
> BetterFoliageLoader (Better-Foliage-2.1.0.jar)
>   mods.betterfoliage.loader.BetterFoliageTransformer
> AppleCore (AppleCore-2.0.1.jar)
>   squeek.applecore.asm.TransformerModuleHandler
> IvToolkit (IvToolkit-1.2.8.5.jar)
> 
> FMLPlugin (Inventory-Tweaks-1.61-58.jar)
>   invtweaks.forge.asm.ContainerTransformer
> StreamsCoreMod (Streams-0.2.1.jar)
>   streams.core.StreamsClassTransformer
> LoadingPluginHardModeTweaks (Hard-Mode-Tweaks-1.2.2.jar)
>   com.hea3ven.hardmodetweaks.core.ClassTransformerHardModeTweaks
> NWRTweak (Redstone-Paste-1.7.4.jar)
>   net.fybertech.nwr.NWRTransformer
>   GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.200.1062.1004' Renderer: 'AMD Radeon HD 6800 Series'
>   Pulsar/tconstruct loaded Pulses: 
>       - TinkerCommons (Enabled/Forced)
>       - TinkerWorld (Enabled/Not Forced)
>       - TinkerTools (Enabled/Not Forced)
>       - TinkerSmeltery (Enabled/Not Forced)
>       - TinkerOredict (Enabled/Forced)
>       - TinkerIntegration (Enabled/Forced)
>       - TinkerFluids (Enabled/Forced)
>       - TinkerMaterials (Enabled/Forced)
>       - chiselsandbitsIntegration (Enabled/Not Forced)
>       - WailaIntegration (Enabled/Not Forced)

**Comment by The-Fireplace** [comment]
Fixed it. Some old files were bundled in that shouldn't have been. The fixed version is waiting for approval on Curse right now.
