### ISSUE TITLE
JEI incompatibility issue

### ISSUE THREAD

**Issue by ghost** [The-Fireplace/Adobe-Blocks#7]
Forge version: 1.10.2-12.18.2.2120
Adobe Blocks version: 6.0.4
JEI version: 3.13.2.360

The Adobe Slab and Adobe Door are listed twice in the JEI item list with the second ones having no texture.

**Comment by The-Fireplace** [comment]
Thanks, I will handle it when I get the chance.

**Comment by ghost** [comment]
Is it unavoidable to make JEI a dependency for the mod to fix the issue?

**Comment by The-Fireplace** [comment]
JEI wasn't made any more of a dependency than it was before, I just marked it as such on the file on CurseForge. It is considered a soft dependency, which means it isn't required in order to run the mod.
